// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcfJ2vh_tP917xJPuVD40UK2CYkMgV9S4',
    appId: '1:1076005395822:web:69750f834090352870f57f',
    messagingSenderId: '1076005395822',
    projectId: 'sportsperson-9d733',
    authDomain: 'sportsperson-9d733.firebaseapp.com',
    storageBucket: 'sportsperson-9d733.appspot.com',
    measurementId: 'G-5D43NDQD2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPypHwrjOLcjD_p6Zm6UhyUiW_vsHCnkM',
    appId: '1:1076005395822:android:ea6d6c11c34dfc6570f57f',
    messagingSenderId: '1076005395822',
    projectId: 'sportsperson-9d733',
    storageBucket: 'sportsperson-9d733.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqbv8eg0Dc8fz5Puq_vRILwF612Oza7BI',
    appId: '1:1076005395822:ios:58ab93b0f3a5982970f57f',
    messagingSenderId: '1076005395822',
    projectId: 'sportsperson-9d733',
    storageBucket: 'sportsperson-9d733.appspot.com',
    iosBundleId: 'com.example.flutterCode',
  );
}
